receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:
  memory_limiter:
    check_interval: 2s
    limit_mib: 400
    spike_limit_mib: 200
  attributes:
    actions:
      - key: service.instance.id
        action: upsert
        value: ${HOSTNAME}

exporters:
  jaeger:
    endpoint: jaeger:14250
    tls:
      # insecure: true
  # logging:
  #   loglevel: warn

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch, attributes]
      exporters: [jaeger]
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [logging]
    # logs:
    #   receivers: [otlp]
    #   processors: [memory_limiter, batch]
    #   exporters: [logging]